#!/bin/bash

#Checking Dependencies
for apps in curl jq; do
	[ ! "$(which "$apps")" ] && echo "Please install $apps!" && exit 1
done

USER=$1

if [ ! "$USER" ]; then
	echo "Username empty" && exit 1
fi

#Fetch!
curl https://api.github.com/users/$USER/events/public | jq '.[] | {type: .type, repo: .repo.name, when: .created_at}'

